run: compile
	@echo "FIXME: *run* should be the default target and compile and execute your code."

compile:
	javac -source 1.7 -target 1.7 -cp FrontEndInterface/JavaFiles/. FrontEndInterface/JavaFiles/*.java

test:
	@echo "FIXME: *test* should run all your group's testing engineer's JUnit tests for the application"

clean:
	$(RM) *.class
